### ISSUE TITLE
error on opening /gatherings tab

### ISSUE THREAD

**Issue by dominictarr** [pietgeursen/patch-gatherings#1]
```
TypeError: s[unit] is not a function
    at handleObject (/home/dominic/c/patchbay/node_modules/spacetime/builds/spacetime.js:1555:14)
    at parseInput (/home/dominic/c/patchbay/node_modules/spacetime/builds/spacetime.js:1589:5)
    at new SpaceTime (/home/dominic/c/patchbay/node_modules/spacetime/builds/spacetime.js:2959:3)
    at main (/home/dominic/c/patchbay/node_modules/spacetime/builds/spacetime.js:1500:10)
    at /home/dominic/c/patchbay/node_modules/pull-stream/throughs/map.js:13:23
    at /home/dominic/c/patchbay/node_modules/pull-stream/throughs/map.js:19:9
    at /home/dominic/c/patchbay/node_modules/pull-stream/throughs/filter.js:17:11
    at /home/dominic/c/patchbay/node_modules/pull-stream/throughs/filter.js:17:11
    at callback (/home/dominic/c/patchbay/node_modules/pull-pushable/index.js:72:5)
    at Function.read.push (/home/dominic/c/patchbay/node_modules/pull-pushable/index.js:39:7)
```

my hunch is that it's just a dependency which isn't up to date.

**Comment by pietgeursen** [comment]
It was a problem with the spacetime module throwing when passed a badly formatted time.

Should be fixed in v2.3.0
